language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

  before_script:

    
  script:
    ./gradlew build --stacktrace
    
